### ISSUE TITLE
No module named 'LMKT_classes'

### ISSUE THREAD

**Issue by freefrog1986** [meghabyte/acl2021-education#1]
when run `python play_qg_model.py -g models/question_generation/spanish_qg` , I got this issue below

```
Traceback (most recent call last):
  File "play_qg_model.py", line 22, in <module>
    from src import generate_questions
  File "/dfs/data/acl2021-education/src/generate_questions.py", line 30, in <module>
    from LMKT_classes import QgGPT2LMHeadModel
ModuleNotFoundError: No module named 'LMKT_classes'
```

**Comment by yichenchou** [comment]
I also have the same problem. Have you solved it?
